#!/bin/sh

[ "$ACTION" = "add" ] || exit 0

case "$INTERFACE" in
usb0|usb1|usb2|eth1|rndis0)
    # 拉接口
    ifconfig "$INTERFACE" up

    # 拿 IP
    udhcpc -i "$INTERFACE" -b -q -t 5
    ;;
esac

exit 0
