#!/bin/sh

uci set network.lan.ipaddr='192.168.0.1'
uci set system.@system[0].hostname='AP8221'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set luci.main.lang='zh_cn'
uci commit
exit 0
