name: Build OpenWrt 23.05
on:
  workflow_dispatch: # 网页手动触发按钮（yml在默认分支才会显示）
  push:
    branches: [ openwrt-23.05 ] # 提交到23.05分支自动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source from openwrt-23.05
        uses: actions/checkout@v4
        with:
          ref: openwrt-23.05 # 重点！拉取你修改过的23.05分支
          fetch-depth: 0
